name: "远程控制"
port: 666
open: false
volume: false
dir: D:\WEB5600\测试文件\files
apps:
  - name: 微信
    path: E:\Program Files (x86)\Tencent\WeChat\WeChat.exe
  - name: 网易云
    path: E:\Program Files (x86)\NetEase\CloudMusic\cloudmusic.exe
